name: go_router_flow
description: A fork of go_router that let's you returns value on pop like navigator 1.0
version: 1.0.0
repository: https://github.com/NazarenoCavazzon/flutter-packages/tree/main/packages/go_router

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
